In [1]:
import pandas as pd
import numpy as np 
import matplotlib.pyplot as plt
from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier
from sklearn.svm import SVC
from sklearn.ensemble import RandomForestClassifier

In [2]:
from sklearn.datasets import load_iris

In [4]:
iris = load_iris()
dir(iris)

['DESCR', 'data', 'feature_names', 'filename', 'target', 'target_names']

In [6]:
from sklearn.model_selection import cross_val_score
cross_val_score(LogisticRegression(),iris.data,iris.target)

c:\users\lenovo\appdata\local\programs\python\python37-32\lib\site-packages\sklearn\linear_model\_logistic.py:940: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  extra_warning_msg=_LOGISTIC_SOLVER_CONVERGENCE_MSG)


array([0.96666667, 1.        , 0.93333333, 0.96666667, 1.        ])

In [8]:
cross_val_score(DecisionTreeClassifier(),iris.data,iris.target)

array([0.96666667, 0.96666667, 0.9       , 1.        , 1.        ])

In [9]:
cross_val_score(SVC(),iris.data,iris.target)

array([0.96666667, 0.96666667, 0.96666667, 0.93333333, 1.        ])

In [10]:
cross_val_score(RandomForestClassifier(),iris.data,iris.target)

array([0.96666667, 0.96666667, 0.93333333, 0.93333333, 1.        ])

In [12]:
def get_score(model,x_train,x_test,y_train,y_test):
    model.fit(x_train,y_train)
    return model.score(x_test,y_test)

from sklearn.model_selection import StratifiedKFold
kfold = StratifiedKFold()

score_lr =[]
score_dt =[]
score_svm =[]
score_rf =[]

for train_index, test_index in kfold.split(iris.data,iris.target):
    x_train,x_test,y_train,y_test = iris.data[train_index],iris.data[test_index], \
                                    iris.target[train_index],iris.target[test_index]
    score_lr.append(get_score(LogisticRegression(),x_train,x_test,y_train,y_test))
    score_dt.append(get_score(DecisionTreeClassifier(),x_train,x_test,y_train,y_test))
    score_svm.append(get_score(SVC(),x_train,x_test,y_train,y_test))
    score_rf.append(get_score(RandomForestClassifier(),x_train,x_test,y_train,y_test))
    


c:\users\lenovo\appdata\local\programs\python\python37-32\lib\site-packages\sklearn\linear_model\_logistic.py:940: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  extra_warning_msg=_LOGISTIC_SOLVER_CONVERGENCE_MSG)


In [13]:
score_lr

[0.9666666666666667, 1.0, 0.9333333333333333, 0.9666666666666667, 1.0]

In [14]:
score_dt

[0.9666666666666667, 0.9666666666666667, 0.9, 1.0, 1.0]

In [15]:
score_svm

[0.9666666666666667,
 0.9666666666666667,
 0.9666666666666667,
 0.9333333333333333,
 1.0]

In [16]:
score_rf

[0.9666666666666667,
 0.9666666666666667,
 0.9333333333333333,
 0.9333333333333333,
 1.0]